prometheus:
  service:
    type: LoadBalancer
    port: 80
    # AWS EKS specific setting
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  prometheusSpec:
    # Expose additional targets which can be discovered by Prometheus
    additionalScrapeConfigs:
      - job_name: 'snaplogic-snaplex-hpa-jcc-autoscale-metrics'
        scrape_interval: 15s
        metrics_path: '/metrics' # default is metrics
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                # default
                # If you install the Snaplex in your own namespace, you have to provide here.
                - snaplogic
        scheme: https
        tls_config:
          insecure_skip_verify: true
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: pod
        - source_labels: [__address__]
          action: replace
          regex: ([^:]+)(?::\d+)?
          replacement: ${1}:8081
          target_label: __address__
        - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_type]
          action: keep
          regex: jcc # Name for the Pod to match
 
grafana:
  # set 'enabled: true' if you want to enable the Grafana dashboard
  enabled: false
  service:
    type: LoadBalancer
    port: 80
    # AWS EKS specific setting
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
 
alertmanager:
  enabled: false