apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: admin-aws-secrets
  namespace: snaplogic
spec:
  provider: aws
  secretObjects:
  - secretName: snaplogic
    type: Opaque
    data:
    - objectName: slusername
      key: username
    - objectName: slpassword
      key: password
  parameters:
    objects: |
        - objectName: "snaplogic"
          objectType: "secretsmanager"
          jmesPath:
            - path: username
              objectAlias: slusername
            - path: password
              objectAlias: slpassword